# generated by datamodel-codegen:
#   filename:  config.yaml
#   timestamp: 2024-06-13T14:33:39+00:00

from __future__ import annotations

from pydantic import BaseModel


class Screen(BaseModel):
    width: int
    height: int
    title: str


class Game(BaseModel):
    tiles: int


class App(BaseModel):
    resource_path: str
    screen: Screen
    game: Game


class Model(BaseModel):
    app: App
