# generated by datamodel-codegen:
#   filename:  config.yaml

from __future__ import annotations

from pydantic import BaseModel


class Screen(BaseModel):
    width: int
    height: int
    title: str


class Game(BaseModel):
    title: str
    tiles: int
    fps: int


class App(BaseModel):
    screen: Screen
    game: Game


class Config(BaseModel):
    app: App
